const fs = require('fs')
const path = require('path')

const mdPath = path.resolve('..', 'stage_1_UG_PG_question_bank.md')
const content = fs.readFileSync(mdPath, 'utf8')

function parseFullBank(rawText) {
  const ugIndex = rawText.indexOf('# Stage 1 UG Adaptive Question Bank')
  const pgHeaderIndex = rawText.indexOf('# PG Bank')
  const pgIndex = rawText.indexOf('# Stage 1 PG Adaptive Question Bank')

  const ugSection = rawText.substring(ugIndex, pgHeaderIndex)
  const pgSection = rawText.substring(pgIndex)

  function parseSection(sectionText, track) {
    const qBlocks = sectionText.split(/###\s+(UG\d+|PG\d+)/g)
    const questions = []

    for (let i = 1; i < qBlocks.length; i += 2) {
      const qId = qBlocks[i].trim()
      const body = qBlocks[i + 1]

      const lines = body.split('\n').map(l => l.trim()).filter(Boolean)
      const questionText = lines[0]

      let type = 'Standard'
      let difficulty = 'Level 1'
      let dimensions = []
      let discriminator = undefined
      let answer = 'A'
      const rawOptions = []

      for (const line of lines) {
        if (line.startsWith('**Type:**')) {
          type = line.replace('**Type:**', '').trim()
        } else if (line.startsWith('**Difficulty:**')) {
          difficulty = line.replace('**Difficulty:**', '').trim()
        } else if (line.startsWith('**Dimensions:**')) {
          dimensions = line.replace('**Dimensions:**', '').split(',').map(d => d.trim()).filter(Boolean)
        } else if (line.startsWith('**Discriminator:**')) {
          discriminator = line.replace('**Discriminator:**', '').trim()
        } else if (line.startsWith('**Answer:**')) {
          answer = line.replace('**Answer:**', '').trim()
        } else if (/^[A-D]\.\s+/.test(line)) {
          const optLetter = line[0]
          const optText = line.substring(2).trim()
          rawOptions.push({ id: optLetter, text: optText })
        }
      }

      // Determine level (1..5)
      let level = 1
      const numMatch = qId.match(/\d+/)
      const qNum = numMatch ? parseInt(numMatch[0], 10) : 1
      if (qNum <= 15) level = 1
      else if (qNum <= 35) level = 2
      else if (qNum <= 60) level = 3
      else if (qNum <= 85) level = 4
      else level = 5

      // Assign dimension weights to options
      // Level 1: Preference questions where each option can have distinct dimension associations or correct answer gets top weight
      const options = rawOptions.map((opt) => {
        const weights = {}
        const isCorrect = opt.id === answer
        
        if (level === 1) {
          // In Level 1 preference questions, option A is aligned with primary dimensions; other options also give partial or domain weights
          if (isCorrect) {
            dimensions.forEach(d => { weights[d] = 5 })
          } else {
            // Secondary distribution
            dimensions.forEach(d => { weights[d] = 1 })
            // Infer secondary dimensions if text hints
            if (/people|social|community/i.test(opt.text)) weights['SO'] = (weights['SO'] || 0) + 4
            if (/business|market|organi/i.test(opt.text)) weights['BU'] = (weights['BU'] || 0) + 4
            if (/design|concept|creative/i.test(opt.text)) weights['CR'] = (weights['CR'] || 0) + 4
            if (/experiment|science|research/i.test(opt.text)) weights['RE'] = (weights['RE'] || 0) + 4
            if (/app|code|prototype|tech/i.test(opt.text)) weights['TC'] = (weights['TC'] || 0) + 4
          }
        } else {
          // Levels 2..5: Objective reasoning / scenario / analytical
          if (isCorrect) {
            dimensions.forEach(d => { weights[d] = 5 })
          } else {
            dimensions.forEach(d => { weights[d] = 1 })
          }
        }

        return {
          id: opt.id,
          text: opt.text,
          weights
        }
      })

      questions.push({
        id: qId,
        number: qNum,
        track,
        level,
        type,
        difficulty,
        dimensions,
        discriminator,
        question: questionText,
        options,
        correctAnswer: answer
      })
    }

    return questions
  }

  const ugQuestions = parseSection(ugSection, 'UG')
  const pgQuestions = parseSection(pgSection, 'PG')

  return { ugQuestions, pgQuestions }
}

const { ugQuestions, pgQuestions } = parseFullBank(content)

console.log(`Successfully parsed ${ugQuestions.length} UG questions and ${pgQuestions.length} PG questions.`)

const tsContent = `/**
 * Stage 1 Adaptive Assessment Question Bank
 * Autogenerated from stage_1_UG_PG_question_bank.md
 * Total: 110 UG Questions + 110 PG Questions across 5 Structured Levels
 */

export interface OptionWeightItem {
  id: 'A' | 'B' | 'C' | 'D'
  text: string
  weights: Record<string, number>
}

export interface Stage1Question {
  id: string
  number: number
  track: 'UG' | 'PG'
  level: 1 | 2 | 3 | 4 | 5
  type: string
  difficulty: string
  dimensions: string[]
  discriminator?: string
  question: string
  options: OptionWeightItem[]
  correctAnswer: string
}

export const STAGE1_DIMENSION_DEFS = {
  AR: { code: 'AR', name: 'Analytical Reasoning', description: 'Pattern finding, root cause investigation and structured logic' },
  LR: { code: 'LR', name: 'Logical Reasoning', description: 'Deductive reasoning, conditional arguments and logic sequences' },
  QR: { code: 'QR', name: 'Quantitative Reasoning', description: 'Mathematical estimation, calculations, charts and numerical models' },
  PS: { code: 'PS', name: 'Problem Solving', description: 'Practical debugging, hands-on diagnostics and system workflows' },
  SC: { code: 'SC', name: 'Scientific Thinking', description: 'Hypothesis testing, empirical methodology and scientific inquiry' },
  RE: { code: 'RE', name: 'Research Orientation', description: 'Evidence synthesis, literature analysis and deep inquiry' },
  TC: { code: 'TC', name: 'Technology Orientation', description: 'Software engineering, algorithms, computing and digital architecture' },
  CR: { code: 'CR', name: 'Creativity & Design', description: 'Visual aesthetics, conceptual ideation and divergent thinking' },
  CO: { code: 'CO', name: 'Communication', description: 'Persuasive articulation, reporting and structured expression' },
  SO: { code: 'SO', name: 'Social Orientation', description: 'Human behavior, community impact, psychology and counseling' },
  LE: { code: 'LE', name: 'Leadership & Management', description: 'Team coordination, governance and project execution' },
  BU: { code: 'BU', name: 'Business Orientation', description: 'Market dynamics, corporate strategy and financial acumen' },
} as const

export const UG_STAGE1_QUESTIONS: Stage1Question[] = ${JSON.stringify(ugQuestions, null, 2)}

export const PG_STAGE1_QUESTIONS: Stage1Question[] = ${JSON.stringify(pgQuestions, null, 2)}

/**
 * Selects 30 questions for an adaptive test (6 from each of the 5 levels).
 */
export function getStage1Questions(track: 'UG' | 'PG', seed = 0): Stage1Question[] {
  const pool = track === 'PG' ? PG_STAGE1_QUESTIONS : UG_STAGE1_QUESTIONS
  const selected: Stage1Question[] = []

  // Group by level 1..5
  for (let lvl = 1; lvl <= 5; lvl++) {
    const levelPool = pool.filter((q) => q.level === lvl)
    // Deterministic or pseudo-random selection of 6 questions per level
    const offset = (seed * 7 + lvl * 3) % levelPool.length
    const picked: Stage1Question[] = []
    for (let i = 0; i < 6; i++) {
      const idx = (offset + i * 2) % levelPool.length
      picked.push(levelPool[idx] || levelPool[i % levelPool.length])
    }
    selected.push(...picked)
  }

  return selected
}

/**
 * PG Eligibility Map: Validates candidate undergraduate degree against eligible PG programs.
 */
export const PG_DEGREE_ELIGIBILITY_MAP: Record<string, string[]> = {
  'B.Tech / B.E': [
    'M.Tech Computer Science & Engineering',
    'M.Tech Artificial Intelligence & Machine Learning',
    'M.Tech Cloud Architecture & DevOps',
    'M.Tech Robotics & Automation',
    'M.Tech Structural Engineering',
    'MBA Technology Management',
    'MBA Business Analytics',
    'M.Sc Data Science & AI',
  ],
  'BCA / B.Sc IT / B.Sc CS': [
    'MCA Enterprise Software & Cloud Computing',
    'MCA AI & Cyber Defense',
    'M.Sc Data Science & Computing',
    'MBA Information Technology',
    'MBA Business Analytics',
  ],
  'B.Com / BBA / BMS': [
    'MBA Financial Management & Fintech',
    'MBA Marketing & Digital Strategy',
    'MBA Human Resource Management',
    'MBA International Business',
    'MBA Business Analytics',
    'M.Com Corporate Accounting & Taxation',
  ],
  'B.Pharm / B.Sc Biotech / Life Sciences': [
    'M.Pharm Pharmaceutics',
    'M.Pharm Pharmacology',
    'M.Pharm Pharmaceutical Chemistry',
    'Pharm.D Post Baccalaureate',
    'M.Sc Biotechnology & Molecular Biology',
    'MBA Healthcare & Hospital Management',
  ],
  'B.Sc (Physics / Chemistry / Maths)': [
    'M.Sc Applied Physics & Nanotechnology',
    'M.Sc Organic Chemistry',
    'M.Sc Mathematical Data Science',
    'MCA Software Engineering',
    'MBA Operations & Tech Management',
  ],
  'BA / LLB / B.Des / Humanities': [
    'LL.M Corporate & Commercial Law',
    'LL.M Criminal & Constitutional Law',
    'M.Des UX/UI & Product Architecture',
    'MBA Human Resource Management',
    'MBA Media & Event Strategy',
  ]
}
`

const outPath = path.resolve(__dirname, 'src', 'lib', 'engines', 'stage1-bank-data.ts')
fs.writeFileSync(outPath, tsContent, 'utf8')
console.log(`Generated ${outPath} (${tsContent.length} bytes)`)
