/**
 * Complete Question Bank for Career Intelligence System
 * Contains 30 UG Questions and 30 PG Questions with exact option-level multi-dimensional weights.
 */

export interface QuestionOptionItem {
  id: 'A' | 'B' | 'C' | 'D'
  text: string
  weights: Record<string, number>
}

export interface BankQuestion {
  id: string
  track: 'UG' | 'PG'
  number: number
  question: string
  options: QuestionOptionItem[]
}

export const UG_QUESTION_BANK: BankQuestion[] = [
  {
    id: 'UG_Q01',
    track: 'UG',
    number: 1,
    question: 'Which activity would you enjoy most?',
    options: [
      { id: 'A', text: 'Solving a difficult logical problem', weights: { ANA: 5 } },
      { id: 'B', text: 'Designing a poster, video, or visual concept', weights: { CRE: 5, SOC: 1 } },
      { id: 'C', text: 'Organising a business activity', weights: { ANA: 1, CRE: 1, BUS: 5, SOC: 1 } },
      { id: 'D', text: 'Understanding how people think and behave', weights: { ANA: 1, BUS: 1, SOC: 5 } },
    ],
  },
  {
    id: 'UG_Q02',
    track: 'UG',
    number: 2,
    question: 'Which subject-related activity attracts you most?',
    options: [
      { id: 'A', text: 'Mathematics and quantitative problems', weights: { NUM: 5, TECH: 1, SCI: 1 } },
      { id: 'B', text: 'Computers and programming', weights: { NUM: 2, TECH: 5, SCI: 1 } },
      { id: 'C', text: 'Biology and human life', weights: { NUM: 1, SCI: 5, SOC: 2 } },
      { id: 'D', text: 'History, society and culture', weights: { SCI: 1, SOC: 5 } },
    ],
  },
  {
    id: 'UG_Q03',
    track: 'UG',
    number: 3,
    question: 'You receive a large amount of data. What would you prefer to do?',
    options: [
      { id: 'A', text: 'Find patterns and relationships', weights: { ANA: 5, BUS: 2 } },
      { id: 'B', text: 'Create charts and visualisations', weights: { ANA: 2, CRE: 5, BUS: 1 } },
      { id: 'C', text: 'Use it to make a business decision', weights: { ANA: 3, BUS: 5, SOC: 1 } },
      { id: 'D', text: 'Read individual cases behind the data', weights: { ANA: 2, CRE: 1, SOC: 5 } },
    ],
  },
  {
    id: 'UG_Q04',
    track: 'UG',
    number: 4,
    question: 'Which type of project would you choose?',
    options: [
      { id: 'A', text: 'Build a software application', weights: { TECH: 5, SCI: 1, BUS: 1, CRE: 2 } },
      { id: 'B', text: 'Conduct a scientific experiment', weights: { TECH: 1, SCI: 5 } },
      { id: 'C', text: 'Develop a business plan', weights: { BUS: 5, CRE: 1 } },
      { id: 'D', text: 'Create a media/design project', weights: { TECH: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q05',
    track: 'UG',
    number: 5,
    question: 'Which problem would you enjoy solving?',
    options: [
      { id: 'A', text: 'How to make a machine more efficient', weights: { PRA: 5, BUS: 2, CRE: 1 } },
      { id: 'B', text: 'How to increase company sales', weights: { PRA: 1, BUS: 5, SOC: 1, CRE: 1 } },
      { id: 'C', text: "How to improve people's wellbeing", weights: { PRA: 2, SOC: 5 } },
      { id: 'D', text: 'How to communicate an idea creatively', weights: { PRA: 1, BUS: 1, SOC: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q06',
    track: 'UG',
    number: 6,
    question: 'How do you normally approach a difficult problem?',
    options: [
      { id: 'A', text: 'Break it into smaller logical parts', weights: { ANA: 5, CRE: 1, PRA: 2 } },
      { id: 'B', text: 'Try several creative approaches', weights: { ANA: 1, CRE: 5, PRA: 2 } },
      { id: 'C', text: 'Discuss it with other people', weights: { ANA: 1, CRE: 1, COM: 5, PRA: 1 } },
      { id: 'D', text: 'Test different practical solutions', weights: { ANA: 2, CRE: 2, PRA: 5 } },
    ],
  },
  {
    id: 'UG_Q07',
    track: 'UG',
    number: 7,
    question: 'Which activity would you willingly spend several hours doing?',
    options: [
      { id: 'A', text: 'Coding or working with technology', weights: { TECH: 5, SCI: 1, BUS: 1, CRE: 1 } },
      { id: 'B', text: 'Reading about scientific discoveries', weights: { TECH: 1, SCI: 5 } },
      { id: 'C', text: 'Analysing a business or financial problem', weights: { TECH: 1, SCI: 1, BUS: 5, CRE: 1 } },
      { id: 'D', text: 'Creating content or visual designs', weights: { TECH: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q08',
    track: 'UG',
    number: 8,
    question: 'Which role would you prefer in a group project?',
    options: [
      { id: 'A', text: 'Technical problem solver', weights: { TECH: 5, LEAD: 1, RES: 2 } },
      { id: 'B', text: 'Team leader', weights: { TECH: 1, LEAD: 5, COM: 2 } },
      { id: 'C', text: 'Researcher', weights: { TECH: 1, RES: 5, COM: 1 } },
      { id: 'D', text: 'Presenter and communicator', weights: { LEAD: 2, RES: 1, COM: 5 } },
    ],
  },
  {
    id: 'UG_Q09',
    track: 'UG',
    number: 9,
    question: 'Which question interests you most?',
    options: [
      { id: 'A', text: 'How does a machine work?', weights: { TECH: 5, BUS: 1, SCI: 3 } },
      { id: 'B', text: 'Why do people behave differently?', weights: { SOC: 5, BUS: 1, SCI: 1 } },
      { id: 'C', text: 'Why do companies succeed or fail?', weights: { TECH: 1, SOC: 1, BUS: 5 } },
      { id: 'D', text: 'How does the natural world work?', weights: { TECH: 1, SOC: 1, SCI: 5 } },
    ],
  },
  {
    id: 'UG_Q10',
    track: 'UG',
    number: 10,
    question: 'Which outcome gives you the most satisfaction?',
    options: [
      { id: 'A', text: 'Finding the correct answer', weights: { ANA: 5, BUS: 1 } },
      { id: 'B', text: 'Creating something original', weights: { ANA: 1, CRE: 5, BUS: 1 } },
      { id: 'C', text: 'Helping someone solve a problem', weights: { ANA: 1, SOC: 5, BUS: 1 } },
      { id: 'D', text: 'Achieving a measurable business result', weights: { ANA: 2, CRE: 1, SOC: 1, BUS: 5 } },
    ],
  },
  {
    id: 'UG_Q11',
    track: 'UG',
    number: 11,
    question: 'Which type of work environment sounds most attractive?',
    options: [
      { id: 'A', text: 'Laboratory', weights: { SCI: 5, TECH: 1 } },
      { id: 'B', text: 'Technology company', weights: { SCI: 2, TECH: 5, BUS: 2, CRE: 1 } },
      { id: 'C', text: 'Corporate office', weights: { TECH: 1, BUS: 5 } },
      { id: 'D', text: 'Creative studio', weights: { TECH: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q12',
    track: 'UG',
    number: 12,
    question: 'Which skill would you most like to develop?',
    options: [
      { id: 'A', text: 'Advanced mathematics', weights: { NUM: 5, TECH: 1 } },
      { id: 'B', text: 'Programming', weights: { NUM: 2, TECH: 5, CRE: 1 } },
      { id: 'C', text: 'Public speaking', weights: { COM: 5, CRE: 1 } },
      { id: 'D', text: 'Design', weights: { TECH: 1, COM: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q13',
    track: 'UG',
    number: 13,
    question: 'When learning something new, you prefer:',
    options: [
      { id: 'A', text: 'Understanding the theory first', weights: { RES: 5, PRA: 1 } },
      { id: 'B', text: 'Trying it practically', weights: { RES: 1, PRA: 5, CRE: 1 } },
      { id: 'C', text: 'Discussing it with others', weights: { RES: 1, PRA: 1, COM: 5 } },
      { id: 'D', text: 'Experimenting with different approaches', weights: { RES: 2, PRA: 3, COM: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q14',
    track: 'UG',
    number: 14,
    question: 'Which type of competition motivates you?',
    options: [
      { id: 'A', text: 'Solving the hardest problem', weights: { ANA: 5, TECH: 1 } },
      { id: 'B', text: 'Building the best product', weights: { ANA: 2, TECH: 5, BUS: 2, CRE: 2 } },
      { id: 'C', text: 'Winning customers or market share', weights: { ANA: 1, BUS: 5, CRE: 1 } },
      { id: 'D', text: 'Creating the most original idea', weights: { ANA: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q15',
    track: 'UG',
    number: 15,
    question: 'Which topic would you voluntarily research?',
    options: [
      { id: 'A', text: 'Artificial intelligence', weights: { TECH: 5, SCI: 2, BUS: 1 } },
      { id: 'B', text: 'Human health', weights: { TECH: 1, SCI: 5, SOC: 2 } },
      { id: 'C', text: 'Financial markets', weights: { TECH: 1, SCI: 1, BUS: 5 } },
      { id: 'D', text: 'Social behaviour', weights: { SCI: 1, BUS: 1, SOC: 5 } },
    ],
  },
  {
    id: 'UG_Q16',
    track: 'UG',
    number: 16,
    question: 'Which task would you prefer?',
    options: [
      { id: 'A', text: 'Analyse a spreadsheet', weights: { NUM: 5, CRE: 1 } },
      { id: 'B', text: 'Conduct an experiment', weights: { NUM: 1, SCI: 5 } },
      { id: 'C', text: 'Interview people', weights: { NUM: 1, SCI: 1, SOC: 5, CRE: 1 } },
      { id: 'D', text: 'Design a campaign', weights: { NUM: 1, SOC: 2, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q17',
    track: 'UG',
    number: 17,
    question: 'Which statement sounds most like you?',
    options: [
      { id: 'A', text: 'I enjoy finding patterns.', weights: { ANA: 5, TECH: 1 } },
      { id: 'B', text: 'I enjoy understanding people.', weights: { ANA: 1, SOC: 5, COM: 2 } },
      { id: 'C', text: 'I enjoy building things.', weights: { ANA: 2, TECH: 5 } },
      { id: 'D', text: 'I enjoy persuading people.', weights: { ANA: 1, SOC: 2, COM: 5 } },
    ],
  },
  {
    id: 'UG_Q18',
    track: 'UG',
    number: 18,
    question: 'What would you rather manage?',
    options: [
      { id: 'A', text: 'A technical project', weights: { TECH: 5, LEAD: 3, CRE: 1 } },
      { id: 'B', text: 'A business team', weights: { TECH: 1, LEAD: 5, SOC: 1, CRE: 1 } },
      { id: 'C', text: 'A social initiative', weights: { LEAD: 3, SOC: 5, CRE: 1 } },
      { id: 'D', text: 'A creative project', weights: { TECH: 1, LEAD: 2, SOC: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q19',
    track: 'UG',
    number: 19,
    question: 'Which decision-making style describes you?',
    options: [
      { id: 'A', text: 'I rely heavily on data', weights: { ANA: 5, SCI: 1, BUS: 2 } },
      { id: 'B', text: 'I rely on evidence and experiments', weights: { ANA: 3, SCI: 5, BUS: 1 } },
      { id: 'C', text: "I consider people's perspectives", weights: { ANA: 1, SOC: 5, BUS: 1 } },
      { id: 'D', text: 'I consider business outcomes', weights: { ANA: 2, SOC: 1, BUS: 5 } },
    ],
  },
  {
    id: 'UG_Q20',
    track: 'UG',
    number: 20,
    question: 'Which activity would you choose during a free workshop?',
    options: [
      { id: 'A', text: 'Coding', weights: { TECH: 5, BUS: 1, CRE: 1 } },
      { id: 'B', text: 'Entrepreneurship', weights: { TECH: 1, BUS: 5, SOC: 1, CRE: 2 } },
      { id: 'C', text: 'Psychology', weights: { BUS: 1, SOC: 5 } },
      { id: 'D', text: 'Graphic design', weights: { TECH: 1, BUS: 1, SOC: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q21',
    track: 'UG',
    number: 21,
    question: 'Which kind of achievement would make you proudest?',
    options: [
      { id: 'A', text: 'Developing a useful technology', weights: { TECH: 5, BUS: 2, SCI: 1, CRE: 1 } },
      { id: 'B', text: 'Starting a successful business', weights: { TECH: 1, BUS: 5, CRE: 2 } },
      { id: 'C', text: 'Making a scientific discovery', weights: { TECH: 1, SCI: 5 } },
      { id: 'D', text: 'Creating something people appreciate', weights: { TECH: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q22',
    track: 'UG',
    number: 22,
    question: 'Which type of uncertainty interests you?',
    options: [
      { id: 'A', text: 'An unanswered scientific question', weights: { SCI: 5, TECH: 1, CRE: 1 } },
      { id: 'B', text: 'An unpredictable business opportunity', weights: { BUS: 5, TECH: 1, CRE: 2 } },
      { id: 'C', text: 'A complex technical problem', weights: { SCI: 2, BUS: 1, TECH: 5, CRE: 1 } },
      { id: 'D', text: 'An unexplored creative concept', weights: { SCI: 1, BUS: 1, TECH: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q23',
    track: 'UG',
    number: 23,
    question: 'Which type of responsibility would you prefer?',
    options: [
      { id: 'A', text: 'Managing people', weights: { LEAD: 5, BUS: 2 } },
      { id: 'B', text: 'Managing money', weights: { LEAD: 2, BUS: 5, RES: 1 } },
      { id: 'C', text: 'Managing technology', weights: { LEAD: 2, BUS: 1, TECH: 5, RES: 1 } },
      { id: 'D', text: 'Managing a research project', weights: { LEAD: 2, BUS: 1, TECH: 1, RES: 5 } },
    ],
  },
  {
    id: 'UG_Q24',
    track: 'UG',
    number: 24,
    question: 'Which statement best describes your relationship with numbers?',
    options: [
      { id: 'A', text: 'I enjoy numerical problems.', weights: { NUM: 5 } },
      { id: 'B', text: 'I can work with numbers when needed.', weights: { NUM: 3, COM: 1, CRE: 1 } },
      { id: 'C', text: 'I prefer words and people.', weights: { COM: 3, SOC: 4 } },
      { id: 'D', text: 'I prefer visual and creative work.', weights: { NUM: 1, SOC: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q25',
    track: 'UG',
    number: 25,
    question: 'Which type of course project would excite you?',
    options: [
      { id: 'A', text: 'Build a working prototype', weights: { PRA: 5, BUS: 1, SCI: 1, CRE: 2 } },
      { id: 'B', text: 'Analyse a company', weights: { PRA: 2, BUS: 5, CRE: 1 } },
      { id: 'C', text: 'Conduct a scientific study', weights: { PRA: 2, SCI: 5 } },
      { id: 'D', text: 'Produce a creative portfolio', weights: { PRA: 1, BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q26',
    track: 'UG',
    number: 26,
    question: 'Which skill is most natural to you?',
    options: [
      { id: 'A', text: 'Logical reasoning', weights: { ANA: 5, CRE: 1 } },
      { id: 'B', text: 'Communication', weights: { ANA: 1, COM: 5, CRE: 2, LEAD: 1 } },
      { id: 'C', text: 'Creative thinking', weights: { ANA: 1, COM: 2, CRE: 5 } },
      { id: 'D', text: 'Organising people', weights: { ANA: 1, COM: 2, CRE: 1, LEAD: 5 } },
    ],
  },
  {
    id: 'UG_Q27',
    track: 'UG',
    number: 27,
    question: 'Which internship would you choose?',
    options: [
      { id: 'A', text: 'Software/technology company', weights: { TECH: 5, BUS: 2, RES: 1, CRE: 1 } },
      { id: 'B', text: 'Bank or financial company', weights: { TECH: 1, BUS: 5, RES: 1 } },
      { id: 'C', text: 'Research laboratory', weights: { TECH: 1, BUS: 1, RES: 5 } },
      { id: 'D', text: 'Advertising/media company', weights: { TECH: 1, BUS: 1, RES: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q28',
    track: 'UG',
    number: 28,
    question: 'What motivates you most?',
    options: [
      { id: 'A', text: 'Intellectual challenge', weights: { ANA: 5, BUS: 1, SOC: 1, CRE: 1 } },
      { id: 'B', text: 'Financial/business success', weights: { ANA: 1, BUS: 5, CRE: 1 } },
      { id: 'C', text: 'Helping people', weights: { ANA: 1, SOC: 5, CRE: 1 } },
      { id: 'D', text: 'Creative freedom', weights: { ANA: 1, BUS: 1, SOC: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q29',
    track: 'UG',
    number: 29,
    question: 'Which type of result do you prefer?',
    options: [
      { id: 'A', text: 'A numerical result', weights: { NUM: 5, SCI: 1, BUS: 1 } },
      { id: 'B', text: 'A scientific finding', weights: { NUM: 1, SCI: 5 } },
      { id: 'C', text: 'A business outcome', weights: { NUM: 1, SCI: 1, BUS: 5, CRE: 1 } },
      { id: 'D', text: 'A creative product', weights: { BUS: 1, CRE: 5 } },
    ],
  },
  {
    id: 'UG_Q30',
    track: 'UG',
    number: 30,
    question: 'If you had to choose one broad direction today, which would you explore first?',
    options: [
      { id: 'A', text: 'Technology and engineering', weights: { TECH: 5, ANA: 3, SCI: 1, CRE: 1 } },
      { id: 'B', text: 'Business and commerce', weights: { TECH: 1, ANA: 2, BUS: 5, SOC: 1, CRE: 1 } },
      { id: 'C', text: 'Science and research', weights: { TECH: 1, ANA: 3, SCI: 5, SOC: 1 } },
      { id: 'D', text: 'Humanities, social sciences and creative fields', weights: { TECH: 1, ANA: 1, BUS: 1, SCI: 1, SOC: 5, CRE: 5 } },
    ],
  },
]

export const PG_QUESTION_BANK: BankQuestion[] = [
  {
    id: 'PG_Q01',
    track: 'PG',
    number: 1,
    question: 'Which type of postgraduate problem interests you most?',
    options: [
      { id: 'A', text: 'A difficult theoretical problem', weights: { ANA: 5, RES: 3, TECH: 1 } },
      { id: 'B', text: 'A real business problem', weights: { ANA: 2, BUS: 5, RES: 1, TECH: 1 } },
      { id: 'C', text: 'An unresolved research question', weights: { ANA: 3, RES: 5, TECH: 2 } },
      { id: 'D', text: 'A technical implementation problem', weights: { ANA: 3, BUS: 1, RES: 2, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q02',
    track: 'PG',
    number: 2,
    question: 'What would you prefer your dissertation/project to involve?',
    options: [
      { id: 'A', text: 'Mathematical modelling', weights: { NUM: 5, RES: 3, BUS: 1, TECH: 1 } },
      { id: 'B', text: 'Experimental research', weights: { NUM: 2, RES: 5, TECH: 1 } },
      { id: 'C', text: 'Business case analysis', weights: { NUM: 2, RES: 2, BUS: 5, TECH: 1 } },
      { id: 'D', text: 'Technology development', weights: { NUM: 2, RES: 2, BUS: 2, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q03',
    track: 'PG',
    number: 3,
    question: 'Which outcome matters most from your postgraduate degree?',
    options: [
      { id: 'A', text: 'Deep expertise', weights: { SPEC: 5, RES: 3, IND: 1 } },
      { id: 'B', text: 'Research contribution', weights: { SPEC: 3, RES: 5, IND: 1 } },
      { id: 'C', text: 'Industry readiness', weights: { SPEC: 2, RES: 1, IND: 5, LEAD: 2 } },
      { id: 'D', text: 'Leadership preparation', weights: { SPEC: 2, RES: 1, IND: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q04',
    track: 'PG',
    number: 4,
    question: 'Which activity would you enjoy most?',
    options: [
      { id: 'A', text: 'Analysing complex datasets', weights: { ANA: 5, RES: 2, STR: 2, TECH: 2 } },
      { id: 'B', text: 'Conducting experiments', weights: { ANA: 2, RES: 5, TECH: 2 } },
      { id: 'C', text: 'Developing a business strategy', weights: { ANA: 2, RES: 1, STR: 5, TECH: 1 } },
      { id: 'D', text: 'Building a technical system', weights: { ANA: 3, RES: 1, STR: 2, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q05',
    track: 'PG',
    number: 5,
    question: 'What type of knowledge do you want to gain?',
    options: [
      { id: 'A', text: 'Advanced theory', weights: { SPEC: 5, PRA: 1, RES: 3, STR: 1 } },
      { id: 'B', text: 'Advanced practical skills', weights: { SPEC: 2, PRA: 5, RES: 1, STR: 1 } },
      { id: 'C', text: 'Research methodology', weights: { SPEC: 3, PRA: 2, RES: 5, STR: 1 } },
      { id: 'D', text: 'Strategic and managerial knowledge', weights: { SPEC: 2, PRA: 2, RES: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q06',
    track: 'PG',
    number: 6,
    question: 'You receive contradictory research findings. What would you do?',
    options: [
      { id: 'A', text: 'Re-examine the theoretical assumptions', weights: { ANA: 5, RES: 3, NUM: 1, STR: 1 } },
      { id: 'B', text: 'Repeat the experiment', weights: { ANA: 2, RES: 5, NUM: 2 } },
      { id: 'C', text: 'Analyse the data and methodology', weights: { ANA: 4, RES: 3, NUM: 5, STR: 1 } },
      { id: 'D', text: 'Compare different perspectives', weights: { ANA: 3, RES: 2, NUM: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q07',
    track: 'PG',
    number: 7,
    question: 'Which career environment interests you most?',
    options: [
      { id: 'A', text: 'Research institution', weights: { RES: 5, IND: 1, TECH: 1, SPEC: 3 } },
      { id: 'B', text: 'Corporate organisation', weights: { RES: 1, IND: 5, TECH: 2, SPEC: 2 } },
      { id: 'C', text: 'Technology company', weights: { RES: 2, IND: 5, TECH: 5, SPEC: 2 } },
      { id: 'D', text: 'Academic institution', weights: { RES: 5, IND: 1, TECH: 1, SPEC: 5 } },
    ],
  },
  {
    id: 'PG_Q08',
    track: 'PG',
    number: 8,
    question: 'Which skill would you most like to master?',
    options: [
      { id: 'A', text: 'Advanced analytics', weights: { ANA: 5, NUM: 5, RES: 1, STR: 2, TECH: 2 } },
      { id: 'B', text: 'Research methodology', weights: { ANA: 3, NUM: 2, RES: 5, STR: 1, TECH: 1 } },
      { id: 'C', text: 'Strategic management', weights: { ANA: 2, NUM: 1, RES: 1, STR: 5, TECH: 1 } },
      { id: 'D', text: 'Technical implementation', weights: { ANA: 3, NUM: 2, RES: 1, STR: 2, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q09',
    track: 'PG',
    number: 9,
    question: 'Which project would you select?',
    options: [
      { id: 'A', text: 'Predict customer behaviour using data', weights: { ANA: 5, NUM: 4, RES: 2, BUS: 4, TECH: 3 } },
      { id: 'B', text: 'Study a scientific phenomenon', weights: { ANA: 3, NUM: 2, RES: 5, TECH: 1 } },
      { id: 'C', text: 'Develop a business expansion strategy', weights: { ANA: 3, NUM: 1, RES: 1, BUS: 5, TECH: 1 } },
      { id: 'D', text: 'Develop a new technology', weights: { ANA: 3, NUM: 2, RES: 2, BUS: 1, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q10',
    track: 'PG',
    number: 10,
    question: 'Which statement best describes your postgraduate goal?',
    options: [
      { id: 'A', text: 'Become a specialist', weights: { SPEC: 5, RES: 2, IND: 2, LEAD: 1 } },
      { id: 'B', text: 'Become a researcher', weights: { SPEC: 3, RES: 5, IND: 1 } },
      { id: 'C', text: 'Become an industry professional', weights: { SPEC: 2, RES: 1, IND: 5, LEAD: 2 } },
      { id: 'D', text: 'Become a leader', weights: { SPEC: 2, RES: 1, IND: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q11',
    track: 'PG',
    number: 11,
    question: 'Which type of analysis interests you?',
    options: [
      { id: 'A', text: 'Statistical analysis', weights: { NUM: 5, RES: 4, BUS: 2, STR: 2 } },
      { id: 'B', text: 'Qualitative research', weights: { NUM: 2, RES: 5, BUS: 1, STR: 2 } },
      { id: 'C', text: 'Financial analysis', weights: { NUM: 4, RES: 1, BUS: 5, STR: 3 } },
      { id: 'D', text: 'Operational analysis', weights: { NUM: 3, RES: 1, BUS: 4, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q12',
    track: 'PG',
    number: 12,
    question: 'Which type of problem would you enjoy solving for months?',
    options: [
      { id: 'A', text: 'A research question with no clear answer', weights: { RES: 5, BUS: 1, TECH: 1, STR: 2 } },
      { id: 'B', text: 'A business problem with measurable results', weights: { RES: 1, BUS: 5, TECH: 2, STR: 4 } },
      { id: 'C', text: 'A complex technical problem', weights: { RES: 2, BUS: 1, TECH: 5, STR: 2 } },
      { id: 'D', text: 'A strategic organisational problem', weights: { RES: 1, BUS: 4, TECH: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q13',
    track: 'PG',
    number: 13,
    question: 'How do you prefer to demonstrate expertise?',
    options: [
      { id: 'A', text: 'Publish research', weights: { RES: 5, PRA: 1, BUS: 1 } },
      { id: 'B', text: 'Build a working solution', weights: { RES: 2, PRA: 5, BUS: 2, LEAD: 1 } },
      { id: 'C', text: 'Solve a business case', weights: { RES: 2, PRA: 2, BUS: 5, LEAD: 2 } },
      { id: 'D', text: 'Lead a project', weights: { RES: 1, PRA: 2, BUS: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q14',
    track: 'PG',
    number: 14,
    question: 'Which type of data would you prefer working with?',
    options: [
      { id: 'A', text: 'Large numerical datasets', weights: { NUM: 5, RES: 3, BUS: 2 } },
      { id: 'B', text: 'Experimental observations', weights: { NUM: 3, RES: 5, BUS: 1 } },
      { id: 'C', text: 'Customer/business data', weights: { NUM: 3, RES: 2, BUS: 5, COM: 1 } },
      { id: 'D', text: 'Textual or qualitative data', weights: { NUM: 1, RES: 4, BUS: 1, COM: 5 } },
    ],
  },
  {
    id: 'PG_Q15',
    track: 'PG',
    number: 15,
    question: 'What attracts you to a specialization?',
    options: [
      { id: 'A', text: 'Intellectual depth', weights: { SPEC: 5, IND: 1, RES: 4, PRA: 1 } },
      { id: 'B', text: 'Job opportunities', weights: { SPEC: 2, IND: 5, RES: 1, PRA: 3 } },
      { id: 'C', text: 'Research opportunities', weights: { SPEC: 3, IND: 1, RES: 5, PRA: 2 } },
      { id: 'D', text: 'Ability to solve practical problems', weights: { SPEC: 2, IND: 3, RES: 1, PRA: 5 } },
    ],
  },
  {
    id: 'PG_Q16',
    track: 'PG',
    number: 16,
    question: 'Which role sounds most attractive?',
    options: [
      { id: 'A', text: 'Data scientist/analyst', weights: { ANA: 5, NUM: 5, RES: 2, STR: 2, TECH: 4 } },
      { id: 'B', text: 'Research scientist', weights: { ANA: 4, NUM: 2, RES: 5, STR: 1, TECH: 3 } },
      { id: 'C', text: 'Consultant/strategist', weights: { ANA: 4, NUM: 2, RES: 1, STR: 5, TECH: 1 } },
      { id: 'D', text: 'Product/technology specialist', weights: { ANA: 3, NUM: 1, RES: 1, STR: 3, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q17',
    track: 'PG',
    number: 17,
    question: 'Which decision-making approach do you prefer?',
    options: [
      { id: 'A', text: 'Evidence and data', weights: { ANA: 5, NUM: 5, RES: 2, BUS: 2, STR: 2 } },
      { id: 'B', text: 'Research findings', weights: { ANA: 3, NUM: 2, RES: 5, BUS: 1, STR: 2 } },
      { id: 'C', text: 'Market information', weights: { ANA: 3, NUM: 2, RES: 2, BUS: 5, STR: 3 } },
      { id: 'D', text: 'Experience and strategic judgement', weights: { ANA: 2, NUM: 1, RES: 1, BUS: 3, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q18',
    track: 'PG',
    number: 18,
    question: 'Which postgraduate course structure would you prefer?',
    options: [
      { id: 'A', text: 'Mostly research', weights: { RES: 5, PRA: 1, IND: 1 } },
      { id: 'B', text: 'Mostly practical projects', weights: { RES: 2, PRA: 5, IND: 2, LEAD: 1 } },
      { id: 'C', text: 'Industry internship + coursework', weights: { RES: 2, PRA: 4, IND: 5, LEAD: 2 } },
      { id: 'D', text: 'Coursework + leadership projects', weights: { RES: 1, PRA: 2, IND: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q19',
    track: 'PG',
    number: 19,
    question: 'Which challenge motivates you?',
    options: [
      { id: 'A', text: 'Finding something nobody has explained', weights: { RES: 5, PRA: 1 } },
      { id: 'B', text: 'Improving an existing system', weights: { RES: 2, PRA: 5, BUS: 3, LEAD: 1 } },
      { id: 'C', text: 'Creating business value', weights: { RES: 1, PRA: 3, BUS: 5, LEAD: 2 } },
      { id: 'D', text: 'Managing a complex team', weights: { RES: 1, PRA: 2, BUS: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q20',
    track: 'PG',
    number: 20,
    question: 'Which postgraduate assignment would you enjoy?',
    options: [
      { id: 'A', text: 'Literature review and research gap analysis', weights: { RES: 5, ANA: 3, STR: 1 } },
      { id: 'B', text: 'Data-driven business case', weights: { RES: 3, ANA: 5, TECH: 2, STR: 4 } },
      { id: 'C', text: 'Technical prototype', weights: { RES: 2, ANA: 2, TECH: 5, STR: 2 } },
      { id: 'D', text: 'Strategic recommendation', weights: { RES: 2, ANA: 3, TECH: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q21',
    track: 'PG',
    number: 21,
    question: 'Which outcome would make your project successful?',
    options: [
      { id: 'A', text: 'New knowledge', weights: { RES: 5, BUS: 1, TECH: 1, STR: 1 } },
      { id: 'B', text: 'Measurable business improvement', weights: { RES: 1, BUS: 5, TECH: 2, STR: 4 } },
      { id: 'C', text: 'Working technology', weights: { RES: 2, BUS: 2, TECH: 5, STR: 2 } },
      { id: 'D', text: 'Strategic organisational change', weights: { RES: 1, BUS: 4, TECH: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q22',
    track: 'PG',
    number: 22,
    question: 'Which environment would you prefer?',
    options: [
      { id: 'A', text: 'Independent research', weights: { RES: 5, IND: 1, TECH: 1, LEAD: 1 } },
      { id: 'B', text: 'Collaborative industry team', weights: { RES: 2, IND: 5, TECH: 2, LEAD: 3 } },
      { id: 'C', text: 'Technical development team', weights: { RES: 2, IND: 4, TECH: 5, LEAD: 2 } },
      { id: 'D', text: 'Management team', weights: { RES: 1, IND: 4, TECH: 1, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q23',
    track: 'PG',
    number: 23,
    question: 'Which subject would you study deeply even without an immediate job benefit?',
    options: [
      { id: 'A', text: 'Advanced theory', weights: { SPEC: 5, RES: 3, TECH: 1, STR: 1 } },
      { id: 'B', text: 'Research methods', weights: { SPEC: 3, RES: 5, TECH: 1, STR: 1 } },
      { id: 'C', text: 'Advanced technology', weights: { SPEC: 3, RES: 2, TECH: 5, STR: 1 } },
      { id: 'D', text: 'Strategic management', weights: { SPEC: 2, RES: 1, TECH: 1, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q24',
    track: 'PG',
    number: 24,
    question: 'Which professional problem interests you?',
    options: [
      { id: 'A', text: 'Predicting future outcomes', weights: { ANA: 5, NUM: 5, PRA: 1, BUS: 2, TECH: 2 } },
      { id: 'B', text: 'Improving processes', weights: { ANA: 3, NUM: 2, PRA: 5, BUS: 3, TECH: 2 } },
      { id: 'C', text: 'Understanding customers', weights: { ANA: 3, NUM: 1, PRA: 2, BUS: 5, TECH: 1 } },
      { id: 'D', text: 'Developing new products', weights: { ANA: 3, NUM: 1, PRA: 4, BUS: 3, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q25',
    track: 'PG',
    number: 25,
    question: 'What type of specialization appeals to you?',
    options: [
      { id: 'A', text: 'Highly quantitative', weights: { NUM: 5, RES: 2, IND: 2 } },
      { id: 'B', text: 'Research intensive', weights: { NUM: 2, RES: 5, IND: 1, COM: 1 } },
      { id: 'C', text: 'Industry focused', weights: { NUM: 2, RES: 1, IND: 5, LEAD: 2, COM: 2 } },
      { id: 'D', text: 'People and leadership focused', weights: { NUM: 1, RES: 1, IND: 2, LEAD: 5, COM: 5 } },
    ],
  },
  {
    id: 'PG_Q26',
    track: 'PG',
    number: 26,
    question: 'Which career progression interests you?',
    options: [
      { id: 'A', text: 'Become a technical specialist', weights: { SPEC: 5, RES: 2, LEAD: 1, STR: 2 } },
      { id: 'B', text: 'Become a researcher', weights: { SPEC: 4, RES: 5, STR: 1 } },
      { id: 'C', text: 'Become a manager', weights: { SPEC: 2, RES: 1, LEAD: 5, STR: 4 } },
      { id: 'D', text: 'Become a consultant', weights: { SPEC: 2, RES: 1, LEAD: 3, STR: 5 } },
    ],
  },
  {
    id: 'PG_Q27',
    track: 'PG',
    number: 27,
    question: 'Which type of project would you avoid least?',
    options: [
      { id: 'A', text: 'Long-term research', weights: { RES: 5, NUM: 1, COM: 1, TECH: 1 } },
      { id: 'B', text: 'Complex numerical analysis', weights: { RES: 3, NUM: 5, COM: 1, TECH: 2 } },
      { id: 'C', text: 'Business presentation', weights: { RES: 1, NUM: 1, COM: 5, TECH: 1 } },
      { id: 'D', text: 'Technical implementation', weights: { RES: 2, NUM: 2, COM: 1, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q28',
    track: 'PG',
    number: 28,
    question: 'Which ability should your postgraduate degree strengthen most?',
    options: [
      { id: 'A', text: 'Analytical ability', weights: { ANA: 5, RES: 2, LEAD: 1, TECH: 1 } },
      { id: 'B', text: 'Research ability', weights: { ANA: 3, RES: 5, LEAD: 1, TECH: 2 } },
      { id: 'C', text: 'Leadership ability', weights: { ANA: 2, RES: 1, LEAD: 5, TECH: 1 } },
      { id: 'D', text: 'Technical ability', weights: { ANA: 3, RES: 2, LEAD: 1, TECH: 5 } },
    ],
  },
  {
    id: 'PG_Q29',
    track: 'PG',
    number: 29,
    question: 'Which statement best describes your ideal career?',
    options: [
      { id: 'A', text: 'I want to become an expert in a specialised field.', weights: { SPEC: 5, RES: 2, IND: 2, LEAD: 1 } },
      { id: 'B', text: 'I want to generate new knowledge.', weights: { SPEC: 3, RES: 5, IND: 1 } },
      { id: 'C', text: 'I want to solve industry problems.', weights: { SPEC: 2, RES: 2, IND: 5, LEAD: 3 } },
      { id: 'D', text: 'I want to lead organisations or teams.', weights: { SPEC: 2, RES: 1, IND: 3, LEAD: 5 } },
    ],
  },
  {
    id: 'PG_Q30',
    track: 'PG',
    number: 30,
    question: 'If you had to choose your broad postgraduate direction today, which would you explore?',
    options: [
      { id: 'A', text: 'Data, technology and analytics', weights: { ANA: 4, NUM: 4, TECH: 5, BUS: 2, RES: 2, SPEC: 3 } },
      { id: 'B', text: 'Business, finance and management', weights: { ANA: 3, NUM: 2, TECH: 1, BUS: 5, RES: 1, SPEC: 3 } },
      { id: 'C', text: 'Research and advanced academics', weights: { ANA: 3, NUM: 2, TECH: 2, BUS: 1, RES: 5, SPEC: 5 } },
      { id: 'D', text: 'Professional/creative specialisation', weights: { ANA: 2, NUM: 1, TECH: 1, BUS: 2, RES: 1, SPEC: 5 } },
    ],
  },
]
